### ISSUE TITLE
走过路过~~

### ISSUE THREAD

**Issue by MyCapitaine** [dingjibang/GDX-Query#1]
query的功能很有趣，不过大概针对weight会更方便？

此外，assertmanager的功能还是比较强大的，我觉得大概不需要懒加载？

**Comment by dingjibang** [comment]
噫，竟然有人开提问hhhh，吓尿我

首先query主要针对的是actor，也不是不可以针对widget……虽然感觉意义不太多（（

嗯，我提供的“懒加载”是，当image对象直到被draw的时候，才会加载自身，而且是异步加载自身，所以游戏加载大量image的时候，会瞬间完成，而不是写一个callback+assetManager（gdx默认的异步加载），或者等候纹理全部加载完成，游戏卡顿一阵（gdx默认的同步加载纹理），前面所说，当image对象直到被draw的时候会开始加载自身，未加载完成的时候，会是透明的一张image（当然，此时你设置x，y，width，rotation之类的，也都没有问题的，所有属性都是有效的）。
总之，使用懒加载image技术后，libgdx呈现的图片加载效果类似网页的加载，会先显示别的东西，比如font之类的，而图片会慢慢加载出来（你没见过什么浏览器是网页全都加载完成才显示出来的吧，都是图片在另一个地方异步加载，文字、css之类的先显示出来），而且代码和同步加载的模式完全相同，预计的加载格式是：

```
Image i=$.lazy("texture file path");
```

或者

```
Image i=new LazyImage(xxxxxx);
```

我还没写……不过已经在我另一个叫gdx-rpg的项目里试验了(com.rpsg.rpg.system.ui.ProxyImage)，目前没任何问题，你可以克隆一份跑一下看看图片加载的酸爽效果（hhhhh
![Image](https://raw.githubusercontent.com/dingjibang/GDX-LAZY-FONT/master/foobar.jpg)

**Comment by MyCapitaine** [comment]
好吧 我只大概的看了一下$.java 还以为是专门给image用的 。。
至于懒加载大概明白是什么意思了 
不过我并没有碰到因为加载图片而卡顿的问题呢=_=（大概图片还不够多）
而且异步的话安全问题也是比较棘手的吧

**Comment by dingjibang** [comment]
安全没问题的，并不是多线程（，
图片多的话，加载确实会卡一下下（，你可以弄个大点的图片（不是图片尺寸大，是文件尺寸大），载入看一下

$.java 针对所有actor对象，不光可以控制组件，也可以控制所有自定义的actor类（

如果你对这个项目感兴趣（，欢迎一起同♂性♂交♂友

看你的赤蛮奇头像，也一定是个东方狗，如果对gdx-rpg项目感兴趣更好了（强行安利模式hhh

**Comment by MyCapitaine** [comment]
举个例子 我每一帧给一个image换一个drawable并在下一帧销毁上一帧的资源 
这样不会出现还没加载好就销毁的问题吗

嘛 大概图片多了以后兴趣会比较大啦 ~  不过会关注一下的
虽然不是特别喜欢2Drpg 不过只要是东方都有爱啦╮(╯▽╰)╭
最近时间不多 不过会关注的

**Comment by dingjibang** [comment]
不会出现这种问题的（，

感谢关注，那么我close这个贴了_(:3」∠)_
